

CREATE DATABASE WEBSERVICES;
 USE WEBSERVICES;

CREATE TABLE ALUMNOS(
  Usuario CHAR(30) PRIMARY KEY,
  Institucion VARCHAR(12)NOT NULL,
  Email VARCHAR(35) NOT NULL,
  Pass VARCHAR(12)NOT NULL);

  INSERT INTO ALUMNOS VALUES('DIANA MILINE GALVEZ PEREZ','SENATI','1315225@senati.pe','j@R8uyXLknfh');
  INSERT INTO ALUMNOS VALUES('NAYELY CEVALLOS GARCIA','SENATI','1233794@senati.pe','BrJDBFh@#ICj');
